# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attendee_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61ttendee_service.proto\x12\tattendees\"\x1d\n\x0f\x41ttendeeRequest\x12\n\n\x02id\x18\x01 \x01(\x04\")\n\x10\x41ttendeesRequest\x12\x15\n\rconference_id\x18\x01 \x01(\x04\"H\n\x10\x41ttendeeResponse\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x04\"@\n\x08\x41ttendee\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x04\x32\xa5\x01\n\tAttendees\x12H\n\x0bGetAttendee\x12\x1a.attendees.AttendeeRequest\x1a\x1b.attendees.AttendeeResponse\"\x00\x12N\n\x16GetConferenceAttendees\x12\x1b.attendees.AttendeesRequest\x1a\x13.attendees.Attendee\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'attendee_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ATTENDEEREQUEST._serialized_start=37
  _ATTENDEEREQUEST._serialized_end=66
  _ATTENDEESREQUEST._serialized_start=68
  _ATTENDEESREQUEST._serialized_end=109
  _ATTENDEERESPONSE._serialized_start=111
  _ATTENDEERESPONSE._serialized_end=183
  _ATTENDEE._serialized_start=185
  _ATTENDEE._serialized_end=249
  _ATTENDEES._serialized_start=252
  _ATTENDEES._serialized_end=417
# @@protoc_insertion_point(module_scope)
